[target.x86_64-unknown-linux-gnu]
linker = "x86_64-unknown-linux-gnu-gcc"
# linker = "zig"
# rustflags = ["-C", "link-arg=-fuse-ld=lld"]

[dependencies.openssl-sys]
version = "0.9.109" # Use your actual version
features = ["vendored"]

